apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: REPLACE_ME_NAME
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - cluster: dev
          - cluster: stage
          - cluster: prod
      - list:
          elements:
          - project: REPLACE_ME_PROJECT
  template:
    metadata:
      name: 'guestbook-{{project}}-{{cluster}}'
    spec:
      project: '{{project}}'
      source:
        repoURL: REPLACE_ME_REPO
        targetRevision: HEAD
        path: configs/guestbook/env/{{cluster}}
      destination:
        name: '{{cluster}}'
        namespace: 'guestbook-{{project}}'

